# Site settings
title: Tobias Nilsson UDM15
email: tn222gf@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  An blog for and presentation of my self and my work of the course 1DV021 @ Len
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:  tn222gf

# Build settings
markdown: kramdown
